stages:
  - test
  - build
  - deploy

test:
  image: node:12.16
  stage: test
  script: 
    - make prepare
    - make test
  only:
    - branches

build:
  image: node:12.16
  stage: build
  script: 
    - make prepare
    - make build
  artifacts:
    paths:
      - lib/
    expire_in: 1 week
  only:
    - schedules
    - master
    - release   
